# App Engine config file

runtime: python37

handlers:
- url: /static/
  static_dir: static

- url: /.*
  secure: always  # Automatically redirects to HTTPS
  script: auto

env_variables:
  ENV_VAR_FILE_PATH: 'static/env.yaml'