# App Engine config file

runtime: python37

handlers:
- url: /stat
  static_dir: stat

- url: /.*
  secure: always  # Automatically redirects to HTTPS
  script: auto

env_variables:
  ENV_VAR_FILE_PATH: 'stat/env.yaml'