# Source
#   Setup for python37
#   https://cloud.google.com/appengine/docs/standard/python3/config/appref
#   HTTPS always for appspot apps       
#   https://stackoverflow.com/questions/5367974/https-only-in-google-app-engine

runtime: python37

handlers:
- url: /.*
  secure: always
  script: auto
