# App Engine config file

runtime: python37

handlers:
- url: /.*
  secure: always  # Automatically redirects to HTTPS
  script: auto

- url: /static
  static_dir: public

env_variables:
  ENV_VAR_FILE_PATH: 'static/env.yaml'