# Sources
# General       https://cloud.google.com/cloud-build/docs/configuring-builds/create-basic-configuration
# App Engine    https://cloud.google.com/source-repositories/docs/quickstart-triggering-builds-with-source-repositories
# Functions     https://medium.com/google-cloud/triggering-cloud-functions-deployments-97691f9b5416

steps:

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]

- name: "gcr.io/cloud-builders/gcloud"
  args: [
      'functions',
      'deploy', 'gcf1_rescale',
      '--source', 'https://source.cloud.google.com/project-ii-gae/project-II-gae/functions',
      '--trigger-bucket', 'project-ii-gae-bucket-1'
  ]

timeout: "1600s"