## Cloud Build instruction file

steps:

### UNIT TESTS

# Google Cloud Functions Tests
- name: 'python:3.7-slim'
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip3 install -r testing/requirements.txt && python testing/TestGCF.py'

# Flask Tests
- name: 'python:3.7-slim'
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip3 install -r testing/requirements.txt && export PYTHONPATH="`pwd`" && python testing/TestFlask.py'

# Integration Tests

- name: 'python:3.7-slim'
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip3 install -r testing/requirements.txt && export PYTHONPATH="`pwd`" && python testing/TestIntegration.py'

### DEPLOYMENT

# Deploy Cloud Functions

- name: "gcr.io/cloud-builders/gcloud"
  args: [
      'functions',
      'deploy',
      'gcf1_rescale',
      '--source=https://source.developers.google.com/projects/project-ii-gae/repos/project-II-gae/moveable-aliases/master/paths/functions',
      '--trigger-bucket=project-ii-gae-bucket-1',
      '--runtime=python37',
      '--region=europe-west1',
      '--env-vars-file=static/env.yaml'
  ]

- name: "gcr.io/cloud-builders/gcloud"
  args: [
      'functions',
      'deploy',
      'gcf2_inform',
      '--source=https://source.developers.google.com/projects/project-ii-gae/repos/project-II-gae/moveable-aliases/master/paths/functions',
      '--trigger-bucket=project-ii-gae-bucket-2',
      '--runtime=python37',
      '--region=europe-west1',
      '--env-vars-file=static/env.yaml'
  ]

- name: "gcr.io/cloud-builders/gcloud"
  args: [
      'functions',
      'deploy',
      'gcf3_vision',
      '--source=https://source.developers.google.com/projects/project-ii-gae/repos/project-II-gae/moveable-aliases/master/paths/functions',
      '--trigger-topic=rescaled-images',
      '--runtime=python37',
      '--region=europe-west1',
      '--env-vars-file=static/env.yaml'
  ]

# Deploy App Engine

- name: "gcr.io/cloud-builders/gcloud"
  args: [
      "app", "deploy", "app.yaml",
      "--stop-previous-version",
      "--promote"
      ]
