# source
# https://cloud.google.com/cloud-build/docs/configuring-builds/create-basic-configuration
# https://cloud.google.com/source-repositories/docs/quickstart-triggering-builds-with-source-repositories

steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"